### ISSUE TITLE
Incompatibility with ImmersivePortals (1.18.1)

### ISSUE THREAD

**Issue by ravenCondol** [TheEpicBlock/PolyMc#125]
Server fails to start. Crashlog below:

```
Starting server...
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[23:47:19] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.11
[23:47:19] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.11
[23:47:20] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d95c8 recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)!
         - You should install any version of fabric-textures-v0 for the optimal experience.
[23:47:20] [main/INFO]: Loading 43 mods:
        - cloth-basic-math 0.6.0 via cloth-config
        - cloth-config 6.0.42 via immersive_portals
        - fabric 0.44.0+1.18
        - fabric-api-base 0.4.1+b4f4f6cdc8 via fabric
        - fabric-api-lookup-api-v1 1.4.0+16d92c47c8 via fabric
        - fabric-biome-api-v1 6.0.1+ded849a9c8 via fabric
        - fabric-command-api-v1 1.1.6+3ac43d95c8 via fabric
        - fabric-commands-v0 0.2.5+b4f4f6cdc8 via fabric
        - fabric-containers-v0 0.1.18+d154e2c6c8 via fabric
        - fabric-content-registries-v0 0.4.5+6f53a73dc8 via fabric
        - fabric-crash-report-info-v1 0.1.8+3ac43d95c8 via fabric
        - fabric-dimensions-v1 2.1.7+43d29571c8 via fabric
        - fabric-entity-events-v1 1.4.5+6b21378ac8 via fabric
        - fabric-events-interaction-v0 0.4.16+bfa23f17c8 via fabric
        - fabric-events-lifecycle-v0 0.2.6+b4f4f6cdc8 via fabric
        - fabric-game-rule-api-v1 1.0.10+3ac43d95c8 via fabric
        - fabric-item-api-v1 1.3.0+691a79b5c8 via fabric
        - fabric-item-groups-v0 0.3.3+3ac43d95c8 via fabric
        - fabric-lifecycle-events-v1 1.4.10+c15ca335c8 via fabric
        - fabric-loot-tables-v1 1.0.8+3ac43d95c8 via fabric
        - fabric-mining-level-api-v1 1.0.3+3ac43d95c8 via fabric
        - fabric-mining-levels-v0 0.1.7+b4f4f6cdc8 via fabric
        - fabric-networking-api-v1 1.0.18+3ac43d95c8 via fabric
        - fabric-networking-v0 0.3.5+b4f4f6cdc8 via fabric
        - fabric-object-builder-api-v1 1.11.0+3b82842ec8 via fabric
        - fabric-object-builders-v0 0.7.8+3ac43d95c8 via fabric
        - fabric-particles-v1 0.2.9+526dc1acc8 via fabric
        - fabric-registry-sync-v0 0.8.5+3ac43d95c8 via fabric
        - fabric-rendering-data-attachment-v1 0.3.4+7242e9d7c8 via fabric
        - fabric-rendering-fluids-v1 0.1.18+3ac43d95c8 via fabric
        - fabric-resource-loader-v0 0.4.11+3ac43d95c8 via fabric
        - fabric-screen-handler-api-v1 1.1.11+3ac43d95c8 via fabric
        - fabric-structure-api-v1 2.0.8+295197a7c8 via fabric
        - fabric-tag-extensions-v0 1.2.5+3ac43d95c8 via fabric
        - fabric-tool-attribute-api-v1 1.3.4+7de09f55c8 via fabric
        - fabric-transfer-api-v1 1.5.5+b4f4f6cdc8 via fabric
        - fabricloader 0.12.11
        - imm_ptl_core 1.1.2 via immersive_portals
        - immersive_portals 1.1.2
        - java 17
        - minecraft 1.18.1
        - polymc 3.3.2+1.18.1
        - q_misc_util 1.1.2 via immersive_portals
[23:47:20] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/opc/minecraft/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=SERVER
[23:47:20] [main/INFO]: Compatibility level set to JAVA_16
[23:47:20] [main/INFO]: CustomPacketDisabler is disabled by config
[23:47:20] [main/WARN]: Error loading class: me/jellysquid/mods/lithium/common/world/chunk/LithiumHashPalette (java.lang.ClassNotFoundException: me/jellysquid/mods/lithium/common/world/chunk/LithiumHashPalette)
[23:47:20] [main/WARN]: @Mixin target me.jellysquid.mods.lithium.common.world.chunk.LithiumHashPalette was not found polymc.mixins.json:block.implementations.PaletteBlockPolyImplementation
[23:47:20] [main/WARN]: Error loading class: me/jellysquid/mods/lithium/common/world/chunk/LithiumHashPalette (java.lang.ClassNotFoundException: me/jellysquid/mods/lithium/common/world/chunk/LithiumHashPalette)
[23:47:20] [main/WARN]: Error loading class: me/jellysquid/mods/lithium/common/world/chunk/LithiumHashPalette (java.lang.ClassNotFoundException: me/jellysquid/mods/lithium/common/world/chunk/LithiumHashPalette)
[23:47:25] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zca000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[23:47:26] [main/INFO]: Immersive Portals Mod Initializing
[23:47:26] [main/INFO]: Dimensional Threading is not present
[23:47:26] [main/INFO]: Pehkui is not present
[23:47:26] [main/INFO]: initializing dedicated server
[23:47:27] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:47:28] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:47:28] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:47:28] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[23:47:28] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[23:47:28] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:47:28] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Tool Attribute API (v1), Immersive Portals)
[23:47:28] [Worker-Main-2/INFO]: Loaded 7 recipes
[23:47:29] [Worker-Main-2/INFO]: Loaded 1141 advancements
[23:47:30] [main/INFO]: Applied 0 biome modifications to 0 of 61 new biomes in 2.020 ms
[23:47:32] [main/INFO]: IP Config Applied
[23:47:32] [Server thread/INFO]: Starting minecraft server version 1.18.1
[23:47:32] [Server thread/INFO]: Loading properties
[23:47:32] [Server thread/INFO]: Default game type: SURVIVAL
[23:47:32] [Server thread/INFO]: Generating keypair
[23:47:32] [Server thread/INFO]: Starting Minecraft server on *:54616
[23:47:32] [Server thread/INFO]: Using epoll channel type
[23:47:32] [Server thread/INFO]: Preparing level "world"
[23:47:34] [Server thread/ERROR]: Mixin apply for mod polymc failed polymc.mixins.json:block.implementations.ChunkDataPlayerProvider -> net.minecraft.class_3898: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_3898::neutralizeCache with priority 1000 cannot inject into net/minecraft/class_3898::method_18715(Lnet/minecraft/class_3222;Lorg/apache/commons/lang3/mutable/MutableObject;Lnet/minecraft/class_2818;)V merged by qouteall.imm_ptl.core.mixin.common.chunk_sync.MixinThreadedAnvilChunkStorage_C with priority 1100 [PREINJECT Applicator Phase -> polymc.mixins.json:block.implementations.ChunkDataPlayerProvider -> Prepare Injections ->  -> redirect$zia000$neutralizeCache(Lorg/apache/commons/lang3/mutable/MutableObject;)Ljava/lang/Object; -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_3898::neutralizeCache with priority 1000 cannot inject into net/minecraft/class_3898::method_18715(Lnet/minecraft/class_3222;Lorg/apache/commons/lang3/mutable/MutableObject;Lnet/minecraft/class_2818;)V merged by qouteall.imm_ptl.core.mixin.common.chunk_sync.MixinThreadedAnvilChunkStorage_C with priority 1100 [PREINJECT Applicator Phase -> polymc.mixins.json:block.implementations.ChunkDataPlayerProvider -> Prepare Injections ->  -> redirect$zia000$neutralizeCache(Lorg/apache/commons/lang3/mutable/MutableObject;)Ljava/lang/Object; -> Prepare]
        at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.class_3215.<init>(class_3215.java:89) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.<init>(class_3218.java:220) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:371) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:327) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:182) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:657) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[23:47:34] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3898 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.class_3215.<init>(class_3215.java:89) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.<init>(class_3218.java:220) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:371) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:327) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:182) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:657) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.11.jar:?]
        ... 11 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [polymc.mixins.json:block.implementations.ChunkDataPlayerProvider] from phase [DEFAULT] in config [polymc.mixins.json] from mod [polymc] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.11.jar:?]
        ... 11 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_3898::neutralizeCache with priority 1000 cannot inject into net/minecraft/class_3898::method_18715(Lnet/minecraft/class_3222;Lorg/apache/commons/lang3/mutable/MutableObject;Lnet/minecraft/class_2818;)V merged by qouteall.imm_ptl.core.mixin.common.chunk_sync.MixinThreadedAnvilChunkStorage_C with priority 1100 [PREINJECT Applicator Phase -> polymc.mixins.json:block.implementations.ChunkDataPlayerProvider -> Prepare Injections ->  -> redirect$zia000$neutralizeCache(Lorg/apache/commons/lang3/mutable/MutableObject;)Ljava/lang/Object; -> Prepare]
        at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.11.jar:?]
        ... 11 more
[23:47:34] [Server thread/ERROR]: This crash report has been saved to: /home/opc/minecraft/./crash-reports/crash-2021-12-14_23.47.34-server.txt
[23:47:34] [Server thread/INFO]: Stopping server
[23:47:34] [Server thread/INFO]: Saving players
[23:47:34] [Server thread/INFO]: Saving worlds
[23:47:34] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8621()" because "$$5" is null
        at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:566) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:613) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3782(class_3176.java:567) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:723) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]```

Let me know if I should add anything more!

**Comment by Kimapr** [comment]
I don't think ImmersivePortals can work with this at all, as it heavily relies on clientmod's rendering. I suggest using [ImmersiveCursedness](https://modrinth.com/mod/immersivecursedness) instead (it works purely server-side).

**Comment by ravenCondol** [comment]
#62 made it seem like it used to work, and sadly Cursedness is not available for 1.18.1

**Comment by TheEpicBlock** [comment]
Immersive Portals doesn't work with PolyMc (although it might work if it's installed on the client?). Will leave this issue open to see if the mixin conflict can be fixed though

**Comment by TheEpicBlock** [comment]
<https://github.com/qouteall/ImmersivePortalsMod/blob/eca754f3d7ee45a7be26898087684080fd6fbbd9/imm_ptl_core/src/main/java/qouteall/imm_ptl/core/mixin/common/chunk_sync/MixinThreadedAnvilChunkStorage_C.java#L111>
Yeah, immersive portals redirects the entire chunk sending code. We could add compatibility inside PolyMC but considering Immersive Portals will never work without the client mod I don't think it's worth the work of doing this.
