### ISSUE TITLE
PolyMC seems to kick everyone out of the server at random everytime /polymer creative is used too much (?)

### ISSUE THREAD

**Issue by MrRubberDucky** [TheEpicBlock/PolyMc#141]
If /polymer creative is used too much on our server, it will randomly disconnect everyone with "java.lang.IllegalArgumentException: The expected number of elements must be nonnegative", players can rejoin again just fine and server doesn't really crash from it. 

I'm not really sure by what it is caused exactly but PolyMC is in the logs so I'm assuming the error lies somewhere here. 
Latest PolyMC 4.0.0 with latest Polymer, this time it's the latest stable version that's released so no latest github commits or anythin like that.

Here's the log:
```
[19:36:13] [Netty Server IO #2/ERROR]: Error receiving packet 102 (-- for the note it can be different packet numbers each time)
java.lang.IllegalArgumentException: The expected number of elements must be nonnegative
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22) ~[?:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.<init>(Object2ObjectOpenHashMap.java:103) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.<init>(Object2ObjectOpenHashMap.java:137) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.<init>(Object2ObjectOpenHashMap.java:148) ~[fastutil-8.5.6.jar:?]
	at net.minecraft.nbt.NbtCompound.copy(NbtCompound:682) ~[?:?]
	at net.minecraft.nbt.NbtCompound.copy(NbtCompound:22) ~[?:?]
	at com.google.common.collect.Maps$9.transformEntry(Maps.java:2053) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.Maps$12.getValue(Maps.java:2101) ~[guava-31.0.1-jre.jar:?]
	at it.unimi.dsi.fastutil.objects.AbstractObject2ObjectMap.putAll(AbstractObject2ObjectMap.java:327) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.putAll(Object2ObjectOpenHashMap.java:246) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.<init>(Object2ObjectOpenHashMap.java:138) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.<init>(Object2ObjectOpenHashMap.java:148) ~[fastutil-8.5.6.jar:?]
	at net.minecraft.nbt.NbtCompound.copy(NbtCompound:682) ~[?:?]
	at net.minecraft.item.ItemStack.copy(ItemStack:416) ~[?:?]
	at io.github.theepicblock.polymc.impl.PolyMapImpl.getClientItem(PolyMapImpl.java:110) ~[PolyMc-4.0.0+1.18.2.jar:?]
	at net.minecraft.network.PacketByteBuf.localvar$djg000$writeItemStackHook(PacketByteBuf:3583) ~[?:?]
	at net.minecraft.network.PacketByteBuf.writeItemStack(PacketByteBuf) ~[?:?]
	at net.minecraft.network.PacketByteBuf.writeCollection(PacketByteBuf:131) ~[?:?]
	at net.minecraft.recipe.Ingredient.write(Ingredient:91) ~[?:?]
	at net.minecraft.recipe.ShapelessRecipe$Serializer.write(ShapelessRecipe:124) ~[?:?]
	at net.minecraft.recipe.ShapelessRecipe$Serializer.write(ShapelessRecipe:79) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.writeRecipe(SynchronizeRecipesS2CPacket:52) ~[?:?]
	at net.minecraft.network.PacketByteBuf.writeCollection(PacketByteBuf:131) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.write(SynchronizeRecipesS2CPacket:27) ~[?:?]
	at xyz.nucleoid.packettweaker.PacketContext.writeWithContext(PacketContext.java:29) ~[packet_tweaker-0.2.0+1.18-pre1-d9af428150ab2387.jar:?]
	at net.minecraft.network.PacketEncoder.redirect$dfj000$writePacket(PacketEncoder:1033) ~[?:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder:45) ~[?:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder:14) ~[?:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
	```

**Comment by TheEpicBlock** [comment]
The issue is happening whilst PolyMc is copying an itemstack. A new hashmap is created based on the old one to store the nbt, which creates a new hashmap with the size of the old one. For some reason the size of the old hashmap is negative though. I'm not *sure* why this happens but I bet it's because of the itemstack being accessed on multiple threads at some point.
