### ISSUE TITLE
Error executing task on Client: Getting block state

### ISSUE THREAD

**Issue by skerit** [TheEpicBlock/PolyMc#151]
There's a client-side error the players on my server have been getting for a few weeks now.
I did some testing and managed to reproduce it locally.
I tested it with vanilla PolyMC 4.1.1, not my fork or Polyvalent ;)

(Reproducing the error is quite annoying though: I just have to log out and log back in a lot of times until it stops working.)

Here's the error:

```
[14:46:20] [Render thread/ERROR]: Error executing task on Client
net.minecraft.class_148: Getting block state
	at net.minecraft.class_2818.method_8320(class_2818.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_12208(class_2818.java:287) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_12201(class_2818.java:315) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_31716(class_2818.java:457) ~[client-intermediary.jar:?]
	at net.minecraft.class_6603.method_38593(class_6603.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_6603.method_38588(class_6603.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_12224(class_2818.java:455) ~[client-intermediary.jar:?]
	at net.minecraft.class_631.method_16020(class_631.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_38539(class_634.java:661) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11128(class_634.java:656) ~[client-intermediary.jar:?]
	at net.minecraft.class_2672.method_11528(class_2672.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_2672.method_11054(class_2672.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1085) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: net.minecraft.class_6558: Missing Palette entry for index 20342.
	at net.minecraft.class_2816.method_12288(class_2816.java:36) ~[client-intermediary.jar:?]
	at net.minecraft.class_2841.method_12331(class_2841.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_2841.method_12321(class_2841.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.class_2826.method_12254(class_2826.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_8320(class_2818.java:181) ~[client-intermediary.jar:?]
	... 34 more
```

The raw blockstate id `20342` is actually the first, non-vanilla blockstate.
It seems as if sometimes modded blockstate ids are sent to the client?

I made a small client-side mod to see where the error occurs, and it's in the `WorldChunk` class:

```
[14:52:37] [Render thread/INFO]: [ClientTest] Problem getting ID 20342 from palette
[14:52:37] [Render thread/INFO]: [ClientTest] WorldChunkMixin error catcher:
[14:52:37] [Render thread/INFO]: [ClientTest]  -- pos: class_2339{x=-1486, y=62, z=2058}
[14:52:37] [Render thread/INFO]: [ClientTest]  -- Chunk: net.minecraft.class_2818@4d9d0889
```

The block at -1486,62,2058 is indeed a modded block.

I have a few performance mods (Lithium/Servercore/Starlight/Carpet) running, maybe those are the cause.
I'll take a look, see if they somehow send chunks to the client circumventing PolyMC.

**Comment by TheEpicBlock** [comment]
Odd, PolyMc's [palette implementation](https://github.com/TheEpicBlock/PolyMc/blob/master/src/main/java/io/github/theepicblock/polymc/mixins/block/implementations/PaletteBlockPolyImplementation.java) works inside the write method. So they'd have to do their own serialization if they'd circumvent PolyMc. Either that or the PolyMap is broken, but I highly doubt that.

**Comment by Patbox** [comment]
It's also possible some mod messes with these, causing PolyMC to fail replacing

**Comment by TheEpicBlock** [comment]
Wait, let me guess. The entire subchunk is filled with a single type of block? It seems like Mojang added a new palette type that went under my nose

**Comment by skerit** [comment]
No, it's a single modded block in a pretty standard subchunk.

I already ruled out ServerCore, but Lithium does have a reimplementation of a palette:
https://github.com/CaffeineMC/lithium-fabric/blob/1.18.x/dev/src/main/java/me/jellysquid/mods/lithium/common/world/chunk/LithiumHashPalette.java

It has a few `this.idList.getRawId(this.get(i))` calls

**Comment by TheEpicBlock** [comment]
We mixin to Lithium's palette. So that should be fine

**Comment by TheEpicBlock** [comment]
Wait a minute. Seeing as that id is quite high, I'm assuming there's an id list palette being used? If there's an id palette we shouldn't be remapping the palette but the data itself. But I don't remember ever implementing such a thing.

**Comment by TheEpicBlock** [comment]
Although that wouldn't explain why it only happens sometimes. (And I doubt you have more than 256 different blockstates in your subchunk)

**Comment by skerit** [comment]
Indeed, there aren't that many different blockstates in the subchunk.
Also: as soon as it happens once, it'll keep on happening until the server is reset.
(So it might take me 30-50 login attempts to trigger the error, from then on out it'll keep happening)

**Comment by skerit** [comment]
I've ruled out most mods by now. One of my own mods uses https://github.com/OnyxStudios/Cardinal-Components-API 
It has some chunk mixins

**Comment by skerit** [comment]
cd363b96d4ddaabbbb5f4da0c7906bb03e7718d4 or 5cd697f2131f9df23f99820b35ce0a52df68b314 seems to have solved the issue (even though there were only 155 items in the subchunk's palette)
