### ISSUE TITLE
Custom items sometimes cause players to disconnect

### ISSUE THREAD

**Issue by skerit** [TheEpicBlock/PolyMc#161]
I'd love to hear your thoughts about this: this is what's happening to some of my players from time to time.
I guess somewhere down the line some kind of item poly is not found, which makes it look for a null value in a certain list?
I just can't seem to find where.

```
[19:57:16] [Netty Epoll Server IO #21/ERROR]: Error receiving packet 77
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:678) ~[fastutil-8.5.6.jar:?]
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$KeyIterator.next(Object2ObjectOpenHashMap.java:1083) ~[fastutil-8.5.6.jar:?]
        at net.minecraft.class_2487.method_10713(class_2487.java:163) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487.method_10555(class_2487.java:476) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487.method_10713(class_2487.java:165) ~[server-intermediary.jar:?]
        at net.minecraft.class_2507.method_10631(class_2507.java:134) ~[server-intermediary.jar:?]
        at net.minecraft.class_2507.method_10628(class_2507.java:99) ~[server-intermediary.jar:?]
        at net.minecraft.class_2540.method_10794(class_2540.java:518) ~[server-intermediary.jar:?]
        at net.minecraft.class_2540.method_10793(class_2540.java:567) ~[server-intermediary.jar:?]
        at net.minecraft.class_2943$1.method_12731(class_2943.java:47) ~[server-intermediary.jar:?]
        at net.minecraft.class_2943$1.method_12715(class_2943.java:44) ~[server-intermediary.jar:?]
        at net.minecraft.class_2945.method_12782(class_2945.java:195) ~[server-intermediary.jar:?]
        at net.minecraft.class_2945.method_12787(class_2945.java:140) ~[server-intermediary.jar:?]
        at net.minecraft.class_2739.method_11052(class_2739.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_2545.method_10838(class_2545.java:45) ~[server-intermediary.jar:?]
        at net.minecraft.class_2545.encode(class_2545.java:14) ~[server-intermediary.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.76.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.76.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.76.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.76.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.76.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.76.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.76.Final.jar:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.76.Final.jar:?]
        at net.minecraft.class_2535.method_36942(class_2535.java:213) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10761(class_2535.java:205) ~[server-intermediary.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-common-4.1.76.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-common-4.1.76.Final.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) [netty-transport-classes-epoll-4.1.76.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.76.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.76.Final.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

When this happens, it'll keep on happening in that area. So those players that got disconnected won't be able to get back on.
If someone else comes near, the same will happen to them.
Only a server restart will help.

**Comment by TheEpicBlock** [comment]
Current hypothesis: the entirety of CustomModelDataPoly isn't threadsafe at the moment. Whilst I find this error really odd, and I kinda doubt it comes from multithreading unless fastutils caches their iterators, it's the only reason I can think of.

**Comment by skerit** [comment]
So I've been running the "vanilla" PolyMC for 2 days now, but the same player just had the issue again.

They're always doing the same thing: stripping logs, upon which I spawn in a custom item entity (bark).

In fact there is 1 more item that has caused other players to get the `this.wrapped` error which has a similar mechanic.
Upon breaking glass without silk touch, I spawn in a custom item "shattered glass shards".

**Comment by TheEpicBlock** [comment]
I'm really really really hoping this fixes this issue. Because this is very cursed and threading is the only thing I can think of that can cause such cursedness.

**Comment by skerit** [comment]
I deployed the changes to my server. Let's see what happens in the next few days.

**Comment by TheEpicBlock** [comment]
I'm going to close this for now. If the bug does happen again please reopen <3
