### ISSUE TITLE
Unable to generate resource pack with current master

### ISSUE THREAD

**Issue by skerit** [TheEpicBlock/PolyMc#170]
The new way of getting the vanilla item seems to always return null.
Checking it now.

```
[23:54:31] [Thread-18/WARN]: Exception whilst generating resources for item.gobber2.gobber2_pickaxe_end
[23:54:31] [Thread-18/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "io.github.theepicblock.polymc.api.resource.json.JModel.getOverrides()" because "clientItemModel" is null
[23:54:31] [Thread-18/INFO]: [STDERR]: 	at io.github.theepicblock.polymc.impl.poly.item.CustomModelDataPoly.addToResourcePack(CustomModelDataPoly.java:258)
[23:54:31] [Thread-18/INFO]: [STDERR]: 	at io.github.theepicblock.polymc.impl.PolyMapImpl.lambda$generateResourcePack$0(PolyMapImpl.java:185)
[23:54:31] [Thread-18/INFO]: [STDERR]: 	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196)
[23:54:31] [Thread-18/INFO]: [STDERR]: 	at io.github.theepicblock.polymc.impl.PolyMapImpl.generateResourcePack(PolyMapImpl.java:183)
[23:54:31] [Thread-18/INFO]: [STDERR]: 	at io.github.theepicblock.polymc.impl.PolyMcCommands.lambda$registerCommands$5(PolyMcCommands.java:103)
[23:54:31] [Thread-18/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23:54:31] [Thread-18/WARN]: Exception whilst generating resources for item.blackblock.warped_bark
[23:54:31] [Thread-18/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "io.github.theepicblock.polymc.api.resource.json.JModel.getOverrides()" because "clientItemModel" is null
[23:54:31] [Thread-18/INFO]: [STDERR]: 	at io.github.theepicblock.polymc.impl.poly.item.CustomModelDataPoly.addToResourcePack(CustomModelDataPoly.java:258)
[23:54:31] [Thread-18/INFO]: [STDERR]: 	at io.github.theepicblock.polymc.impl.PolyMapImpl.lambda$generateResourcePack$0(PolyMapImpl.java:185)
[23:54:31] [Thread-18/INFO]: [STDERR]: 	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196)
[23:54:31] [Thread-18/INFO]: [STDERR]: 	at io.github.theepicblock.polymc.impl.PolyMapImpl.generateResourcePack(PolyMapImpl.java:183)
[23:54:31] [Thread-18/INFO]: [STDERR]: 	at io.github.theepicblock.polymc.impl.PolyMcCommands.lambda$registerCommands$5(PolyMcCommands.java:103)
[23:54:31] [Thread-18/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23:54:31] [Thread-18/ERROR]: Error reading vanilla armor textures, please report this
[23:54:31] [Thread-18/INFO]: [STDERR]: java.lang.NullPointerException
[23:54:31] [Thread-18/INFO]: [STDERR]: 	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
[23:54:31] [Thread-18/INFO]: [STDERR]: 	at io.github.theepicblock.polymc.impl.poly.item.ArmorColorManager.addToResourcePack(ArmorColorManager.java:103)
[23:54:31] [Thread-18/INFO]: [STDERR]: 	at io.github.theepicblock.polymc.impl.PolyMapImpl.lambda$generateResourcePack$2(PolyMapImpl.java:205)
[23:54:31] [Thread-18/INFO]: [STDERR]: 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
[23:54:31] [Thread-18/INFO]: [STDERR]: 	at io.github.theepicblock.polymc.impl.PolyMapImpl.generateResourcePack(PolyMapImpl.java:203)
[23:54:31] [Thread-18/INFO]: [STDERR]: 	at io.github.theepicblock.polymc.impl.PolyMcCommands.lambda$registerCommands$5(PolyMcCommands.java:103)
[23:54:31] [Thread-18/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23:54:31] [Thread-18/INFO]: There have been errors whilst generating the resource pack. These are usually completely normal. It only means that PolyMc couldn't find some of the textures or models. See the console for more info.
```

**Comment by skerit** [comment]
Found the issue!
