### ISSUE TITLE
OutOfBounds error in PacketConsumer#sendPacket()

### ISSUE THREAD

**Issue by skerit** [TheEpicBlock/PolyMc#193]
I suddenly had this error crash my server twice in a short time:

```
-- Head --
Thread: Server thread
Stacktrace:
    at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
    at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
    at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
    at java.base/java.util.Objects.checkIndex(Objects.java:359)
    at java.base/java.util.ArrayList.get(ArrayList.java:427)
    at io.github.theepicblock.polymc.impl.poly.wizard.PacketCountManager$TrackingPacketConsumer.sendPacket(PacketCountManager.java:278)
    at rocks.blackblock.polymcplus.wizard.VArmorStand.sendHeadRotation(VArmorStand.java:44)
    at rocks.blackblock.polymcplus.wizard.VArmorStand.sendHeadRotation(VArmorStand.java:48)
    at rocks.blackblock.belongings.compat.PedestalWizard.onTick(PedestalWizard.java:83)
    at io.github.theepicblock.polymc.impl.poly.wizard.RegularWizardUpdater.lambda$tick$1(RegularWizardUpdater.java:55)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
    at io.github.theepicblock.polymc.impl.poly.wizard.RegularWizardUpdater.tick(RegularWizardUpdater.java:53)
    at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:108)
    at net.minecraft.class_3218.handler$bel000$endWorldTick(class_3218.java:8229)
```

I'm guessing some threading issue maybe?
A listener might get removed from the list while `sendPacket` is iterating over it?

**Comment by TheEpicBlock** [comment]
Both of those are unlikely. It's running on the main thread and using its own arraylist. If it was modified whilst iterating it would be a CME. The code is using `listeners` size for both the `listeners` and `trackers` so there's likely more listeners than trackers. I don't see anything in the code that could do this though, are you adding listeners to the arraylist?

**Comment by TheEpicBlock** [comment]
Actually, it might still be a threading issue if one of the arraylists is updated before the other. That's likely it

**Comment by skerit** [comment]
I haven't touched the internals of that part of the code yet, so I'm not manually adding any listeners or so.
I *am* using Dimensional Threading.

**Comment by TheEpicBlock** [comment]
There's a single packet consumer that always gets reused. So this is 100% dimensional threading. One thread might reset the packet consumer whilst another is still using it. Wrapping it in a threadlocal should be a nice and easy fix
