### ISSUE TITLE
Vanilla client cannot handle modded particle types in biome settings

### ISSUE THREAD

**Issue by unilock** [TheEpicBlock/PolyMc#251]
As seen with [Biomes O' Plenty](https://modrinth.com/mod/biomes-o-plenty):

```
[10:08:36] [Render thread/ERROR]: Registry loading errors:
> Errors in registry minecraft:worldgen/biome:
>> Errors in element biomesoplenty:end_corruption:
java.lang.IllegalStateException: Failed to parse value {downfall:0.5f,effects:{fog_color:10518688,foliage_color:4764952,grass_color:8174955,mood_sound:{block_search_extent:8,offset:2.0d,sound:"minecraft:ambient.cave",tick_delay:6000},particle:{options:{type:"biomesoplenty:binary"},probability:3.75E-4f},sky_color:0,water_color:4159204,water_fog_color:329011},has_precipitation:0b,temperature:0.5f} from server
	at akm.a(SourceFile:277)
	at akm$a.a(SourceFile:100)
	at akm.a(SourceFile:155)
	at akm.a(SourceFile:164)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at akm.a(SourceFile:164)
	at akm.a(SourceFile:155)
	at fzs$a.a(SourceFile:49)
	at fzs.a(SourceFile:59)
	at fzd.a(SourceFile:117)
	at fzd.a(SourceFile:109)
	at fzd.a(SourceFile:117)
	at abd.a(SourceFile:22)
	at abd.a(SourceFile:8)
	at zj.a(SourceFile:27)
	at bph.d(SourceFile:162)
	at bpl.d(SourceFile:23)
	at bph.B(SourceFile:136)
	at bph.bB(SourceFile:121)
	at fgo.c(SourceFile:1240)
	at fgo.f(SourceFile:882)
	at net.minecraft.client.main.Main.main(SourceFile:256)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.IllegalStateException: Unknown registry key in ResourceKey[minecraft:root / minecraft:particle_type]: biomesoplenty:binary
	at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287)
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81)
	at akm.a(SourceFile:274)
	... 24 more
```

Minecraft 1.21.1 + Fabric Loader 0.16.7 + PolyMc 5.7.0 (#248)

**Comment by CamperSamu** [comment]
As a temporary workaround, you can override those via Datapack
