### ISSUE TITLE
Unable to open vanilla block guis with modded and vanilla clients

### ISSUE THREAD

**Issue by TrueCP6** [TheEpicBlock/PolyMc#31]
Tested with furnaces, crafting tables and chests. When doing so this exception is spammed to console:
```
[19:10:27] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
        at net.minecraft.class_3944.redirect$zfh000$handlerId(class_3944.java:534) ~[intermediary-server.jar:?]
        at net.minecraft.class_3944.<init>(class_3944.java:22) ~[intermediary-server.jar:?]
        at net.minecraft.class_3222.method_17355(class_3222.java:952) ~[intermediary-server.jar:?]
        at net.minecraft.class_2304.method_9534(class_2304.java:31) ~[intermediary-server.jar:?]
        at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:893) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.redirect$zmc000$activateWithOptionalCactus(class_3225.java:2029) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java:328) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:976) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:724) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zjn000$modifiedRunLoop(MinecraftServer.java:3805) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:653) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
```

**Comment by TheEpicBlock** [comment]
I messed up in the release on Github. Please download the latest build from https://theepicblock.nl/builds/
I'll add a new release on Github soon :)
