### ISSUE TITLE
Failed to get resource from mod jar 'immersive_portals'

### ISSUE THREAD

**Issue by Mhowser** [TheEpicBlock/PolyMc#62]
When I did /polymc gen_resources I get the following error in my server's console

```
Failed to get resource from mod jar 'immersive_portals' path: assets/immersive_portals/blockstates/nether_portal_block.json 
[06:26:38] [Server thread/WARN]: Exception whilst generating resources for block.immersive_portals.nether_portal_block                                       
[06:26:38] [Server thread/INFO]: [STDERR]: java.lang.NullPointerException: in == null                                                                        
[06:26:38] [Server thread/INFO]: [STDERR]:      at com.google.gson.stream.JsonReader.<init>(JsonReader.java:291)                                             
[06:26:38] [Server thread/INFO]: [STDERR]:      at io.github.theepicblock.polymc.api.block.UnusedBlockStatePoly.AddToResourcePack(UnusedBlockStatePoly.java:116)                                                                                                                                                          
[06:26:38] [Server thread/INFO]: [STDERR]:      at io.github.theepicblock.polymc.resource.ResourcePackGenerator.lambda$generate$1(ResourcePackGenerator.java:75)                                                                                                                                                          
[06:26:38] [Server thread/INFO]: [STDERR]:      at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:146)                       
[06:26:38] [Server thread/INFO]: [STDERR]:      at io.github.theepicblock.polymc.resource.ResourcePackGenerator.generate(ResourcePackGenerator.java:73)      
[06:26:38] [Server thread/INFO]: [STDERR]:      at io.github.theepicblock.polymc.PolyMcCommands.lambda$registerCommands$2(PolyMcCommands.java:53)            
[06:26:38] [Server thread/INFO]: [STDERR]:      at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)                                
[06:26:38] [Server thread/INFO]: [STDERR]:      at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176)                                
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2170.method_9249(class_2170.java:249)                                                 
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_14370(class_3244.java:1211)                                               
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_31286(class_3244.java:1198)                                               
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_12048(class_3244.java:1177)                                               
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2797.method_12115(class_2797.java:36)                                                 
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2797.method_11054(class_2797.java:9)                                                  
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2600.method_11072(class_2600.java:21)                                                 
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3738.run(class_3738.java:18)                                                          
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_18859(class_1255.java:144)                                                
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_4093.method_18859(class_4093.java:23)                                                 
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761)                               
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155)                               
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_16075(class_1255.java:118)                                                
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743)                               
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737)                               
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_18857(class_1255.java:127)                                                
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722)                               
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.handler$bad000$modifiedRunLoop(MinecraftServer.java:7319)
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651)
[06:26:38] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[06:26:38] [Server thread/INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:832)
[06:26:39] [Server thread/INFO]: [Cosmocrat: Finished generating]
```

Now I know that Immersive Portals is pretty much needed on the client, but mainly why I posted this issue is because there was no indication of a failure in the game. the chat said 'finished generating' normally, but it would be very helpful if PolyMC could show an error message ingame when something like this happens. Also if you manage to fix whatever went wrong with Immersive Portal that would be very cool.

This is the the version I'm using https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod/files/3138143

**Comment by Obydux** [comment]
[Immersive Cursedness](https://github.com/TheEpicBlock/immersive-cursedness) is a mod similar to Immersive Portals also made by the creator of PolyMc that works on just server-side

**Comment by TheEpicBlock** [comment]
The block probably doesn't have a model or its defined in a nonstandard way; this is more of a warning then an error. I'll look into what Immersive cursedness is doing exactly, maybe it can be fixed. The error message should also be made a bit clearer to reflect this. 
Showing a warning to the command source is also a great idea and will be added 👍

**Comment by TheEpicBlock** [comment]
Just looked at Immersive portals, looks like that block is supposed to be invisible. The method isn't clientside so we can account for it during poly generation. Will be done soon™

**Comment by Mhowser** [comment]
Thankyou for taking care of this!

**Comment by TheEpicBlock** [comment]
With 248d1614422dd618b35c6d5ef0fb978a862a18f4 the logging has been improved.
